version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0
  gcp-gcr: circleci/gcp-gcr@0.15.1

workflows:
  test-build-publish:
    jobs:
      - gradle/test
      - gcp-gcr/build-and-push-image:
          image: 'gcr.io/${GOOGLE_PROJECT_ID}/index-api-<< pipeline.git.branch >>-${CIRCLE_SHA1}'
          registry-url: eu.gcr.io
          filters:
            branches:
              only:
                - main
                - test
