version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0
  gcp-gcr: circleci/gcp-gcr@0.15.0
  twist: doist/twist@0.0.2

jobs:
  twist-notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - twist/notify

workflows:
  test-build-publish:
    jobs:
      - gradle/test:
          name: test
          executor: default
          tag: '20.0.1'
      - gcp-gcr/build-and-push-image:
          name: build-and-push-image
          image: 'index-api-<< pipeline.git.branch >>'
          registry-url: eu.gcr.io
          requires: [test]
          filters:
            branches:
              only:
                - main
                - test
      - twist-notify:
          requires: [build-and-push-image]
