apiVersion: v1
kind: Service
metadata:
  name: index-api-beta
  labels:
    app: index-api-beta
spec:
  selector:
    app: index-api-beta
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
