apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: index-api-stable
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: index-api-stable
                port:
                  number: 80
