apiVersion: v1
kind: Service
metadata:
  name: index-api
  namespace: index
  labels:
    app: index-api
spec:
  selector:
    app: index-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
