version: "3.8"
name: "index-backend-staging-env"

services:
  api:
    image: eu.gcr.io/index-352608/index-api-staging:latest
    container_name: ${COMPOSE_PROJECT_NAME}-api
    env_file:
      - .env
    volumes:
      - $HOME/.config/gcloud/gcp-service-account.json:/gcp/gcp-service-account.json:ro
    ports:
      - "8080:${API_PORT}"
    networks:
      - index-staging-postgres-network
      - index-staging-redis-network
      - index-staging-monitor-network
    depends_on:
      - postgres
      - redis
      - prometheus
  postgres:
    image: postgres
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    restart: no
    environment:
      POSTGRES_DB: indexstagingdb
      POSTGRES_USER: IndexStagingUser
      POSTGRES_PASSWORD: IndexStagingPassword
    volumes:
      - index-staging-pgdata:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
    networks:
      - index-staging-postgres-network
  adminer:
    image: adminer
    container_name: ${COMPOSE_PROJECT_NAME}-adminer
    restart: no
    ports:
      - "8081:8080"
    networks:
      - index-staging-postgres-network
  redis:
    image: redis:latest
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    restart: no
    volumes:
      - index-staging-redis:/data
#    ports:
#      - "6379:6379"
    networks:
      - index-staging-redis-network
  redis-insight:
    image: redislabs/redisinsight
    container_name: ${COMPOSE_PROJECT_NAME}-redis-insight
    restart: no
    ports:
      - "8082:8001"
    networks:
      - index-staging-redis-network
  prometheus:
    image: prom/prometheus
    container_name: ${COMPOSE_PROJECT_NAME}-prometheus
    restart: no
#    ports:
#      - "9090:9090"
    volumes:
      - "./prometheus-monitoring.yml:/etc/prometheus/prometheus.yml"
    networks:
      - index-staging-monitor-network
  grafana:
    image: grafana/grafana
    container_name: ${COMPOSE_PROJECT_NAME}-grafana
    restart: no
    ports:
      - "3000:3000"
    volumes:
      - index-staging-grafana-storage:/var/lib/grafana
    networks:
      - index-staging-monitor-network

volumes:
  index-staging-redis: {}
  index-staging-pgdata: {}
  index-staging-grafana-storage: {}

networks:
  index-staging-redis-network:
    name: index-staging-redis-network
  index-staging-postgres-network:
    name: index-staging-postgres-network
  index-staging-monitor-network:
    name: index-staging-monitor-network