version: "3.8"
services:
  index:
    image: eu.gcr.io/index-352608/index-api-test:latest
    container_name: "index-api"
    depends_on:
      - index-redis
    env_file:
      - .env
    ports:
      - "8080:${PORT}"
    networks:
      - index-network
  index-redis:
    image: redis:latest
    container_name: "index-redis"
    restart: always
    command: redis-server
    volumes:
      - redis:/data
    networks:
      - index-network

volumes:
  redis:

networks:
  index-network:
    name: index-network
