version: "3.8"
name: "index-monitoring-environment"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "../prometheus/prometheus-monitoring.yml:/etc/prometheus/prometheus.yml"
    networks:
      - monitor-net
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitor-net

networks:
  monitor-net:
    name: monitor-net