#version: "3.8"
#name: "index-frontend-dev-env"
#
#services:
#  index:
#    image: eu.gcr.io/index-352608/index-api-main:latest
#    container_name: "index-api"
#    env_file:
#      - .env
#    volumes:
#      - $HOME/.config/gcloud/gcp-service-account.json:/gcp/gcp-service-account.json:ro
#    ports:
#      - "8080:${API_PORT}"
#  prometheus:
#    image: prom/prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
#    networks:
#      - monitor-net
#  grafana:
#    image: grafana/grafana
#    ports:
#      - "3000:3000"
#    volumes:
#      - grafana-storage:/var/lib/grafana
#    networks:
#      - monitor-net
#
#volumes:
#  grafana-storage: {}
#
#networks:
#  monitor-net:
#    name: monitor-net