version: "3.8"
name: "index-dev-environment"
services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: indexdevdb
      POSTGRES_USER: IndexDevUser
      POSTGRES_PASSWORD: IndexDevPassword
    volumes:
      - index-dev-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - index-dev-postgres-network
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - index-dev-postgres-network
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - index-dev-redis:/data
    ports:
      - "6379:6379"
    networks:
      - index-dev-redis-network
  redis-insight:
    image: redislabs/redisinsight
    restart: unless-stopped
    ports:
      - "8082:8001"
    networks:
      - index-dev-redis-network
  rabbit:
    image: rabbitmq:3.9-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "8083:15672"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "../config/prometheus/prometheus-monitoring.yml:/etc/prometheus/prometheus.yml"
    networks:
      - index-dev-monitor-network
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - index-dev-grafana-storage:/var/lib/grafana
    networks:
      - index-dev-monitor-network

volumes:
  index-dev-redis: {}
  index-dev-pgdata: {}
  index-dev-rabbit: {}
  index-dev-grafana-storage: {}

networks:
  index-dev-redis-network:
    name: index-dev-redis-network
  index-dev-postgres-network:
    name: index-dev-postgres-network
  index-dev-monitor-network:
    name: index-dev-monitor-network