version: "3.8"
name: "index-dev-environment"
services:
  index-postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: indexdevdb
      POSTGRES_USER: IndexDevUser
      POSTGRES_PASSWORD: IndexDevPassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres-network
  index-adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - postgres-network
  index-redis:
    image: redis:latest
    container_name: "index-redis"
    restart: unless-stopped
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - redis-network
  index-redis-insight:
    image: redislabs/redisinsight
    container_name: "index-redis-insight"
    restart: unless-stopped
    ports:
      - "8082:8001"
    networks:
      - redis-network
  index-rabbit:
    image: rabbitmq:3.9-management
    container_name: "index-rabbit"
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "8083:15672"
volumes:
  redis:
  pgdata:
  rabbit:

networks:
  redis-network:
    name: redis-network
  postgres-network:
    name: postgres-network