version: "3.8"
name: "index-backend-dev-env"

services:
  postgres:
    image: postgres
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    restart: no
    environment:
      POSTGRES_DB: indexdevdb
      POSTGRES_USER: IndexDevUser
      POSTGRES_PASSWORD: IndexDevPassword
    volumes:
      - index-dev-pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - index-dev-postgres-network
  adminer:
    image: adminer
    container_name: ${COMPOSE_PROJECT_NAME}_adminer
    restart: no
    ports:
      - "8081:8080"
    networks:
      - index-dev-postgres-network
  redis:
    image: redis:latest
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    restart: no
    volumes:
      - index-dev-redis:/data
    ports:
      - "6379:6379"
    networks:
      - index-dev-redis-network
  redis-insight:
    image: redislabs/redisinsight
    container_name: ${COMPOSE_PROJECT_NAME}-redis-insight
    restart: no
    ports:
      - "8082:8001"
    networks:
      - index-dev-redis-network
  rabbit:
    image: rabbitmq:3.9-management
    container_name: ${COMPOSE_PROJECT_NAME}-rabbit
    restart: no
    ports:
      - "5672:5672"
      - "8083:15672"

volumes:
  index-dev-redis: {}
  index-dev-pgdata: {}
  index-dev-rabbit: {}

networks:
  index-dev-redis-network:
    name: index-dev-redis-network
  index-dev-postgres-network:
    name: index-dev-postgres-network