global:
  defaultStorageClass: "longhorn"

architecture: standalone
clusterDomain: gport.giuliopime.dev

auth:
  existingSecret: "rediscreds"
  existingSecretPasswordKey: "password"

commonConfiguration: |-
  save "3600 1 300 100 60 10000"

master:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1024Mi
  persistence:
    size: 3Gi
replica:
  replicaCount: 0
