CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY, email VARCHAR(150) NOT NULL, password_hash VARCHAR(100) NULL, email_verified BOOLEAN NOT NULL, created_at BIGINT NOT NULL, creation_source VARCHAR(10) NOT NULL);
ALTER TABLE users ADD CONSTRAINT users_email_unique UNIQUE (email);
CREATE TABLE IF NOT EXISTS passwordreset (id SERIAL PRIMARY KEY, token VARCHAR(100) NOT NULL, id_user uuid NOT NULL, created_at BIGINT NOT NULL, expires_at BIGINT NOT NULL, CONSTRAINT fk_passwordreset_id_user__id FOREIGN KEY (id_user) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT);
ALTER TABLE passwordreset ADD CONSTRAINT passwordreset_token_unique UNIQUE (token);
CREATE INDEX passwordreset_id_user ON passwordreset (id_user);
CREATE TABLE IF NOT EXISTS emailverification (id SERIAL PRIMARY KEY, token VARCHAR(100) NOT NULL, id_user uuid NOT NULL, created_at BIGINT NOT NULL, expires_at BIGINT NOT NULL, CONSTRAINT fk_emailverification_id_user__id FOREIGN KEY (id_user) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT);
ALTER TABLE emailverification ADD CONSTRAINT emailverification_token_unique UNIQUE (token);
CREATE INDEX emailverification_id_user ON emailverification (id_user);
CREATE TABLE IF NOT EXISTS list (id uuid PRIMARY KEY, id_user uuid NOT NULL, ix_name VARCHAR(100) NOT NULL, emoji CHAR NOT NULL, color VARCHAR(9) NOT NULL, created_at BIGINT NOT NULL, edited_at BIGINT NULL, CONSTRAINT fk_list_id_user__id FOREIGN KEY (id_user) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE INDEX list_id_user ON list (id_user);
CREATE TABLE IF NOT EXISTS category (id uuid PRIMARY KEY, id_user uuid NOT NULL, id_list uuid NOT NULL, ix_name VARCHAR(50) NOT NULL, color VARCHAR(9) NOT NULL, CONSTRAINT fk_category_id_user__id FOREIGN KEY (id_user) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT, CONSTRAINT fk_category_id_list__id FOREIGN KEY (id_list) REFERENCES list(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE INDEX category_id_user ON category (id_user);
CREATE INDEX category_id_list ON category (id_list);
CREATE TABLE IF NOT EXISTS task (id uuid PRIMARY KEY, id_user uuid NOT NULL, id_item uuid NULL, ix_name VARCHAR(150) NOT NULL, description VARCHAR(500) NULL, due_date BIGINT NULL, completed BOOLEAN NOT NULL, priority INT NULL, created_at BIGINT NOT NULL, edited_at BIGINT NULL, completed_at BIGINT NULL);
CREATE TABLE IF NOT EXISTS item (id uuid PRIMARY KEY, id_user uuid NOT NULL, id_list uuid NOT NULL, id_category uuid NOT NULL, id_task uuid NULL, ix_name VARCHAR(150) NOT NULL, completed BOOLEAN NOT NULL, created_at BIGINT NOT NULL, edited_at BIGINT NULL, completed_at BIGINT NULL);
CREATE INDEX item_id_user ON item (id_user);
CREATE INDEX item_id_list ON item (id_list);
CREATE INDEX item_id_category ON item (id_category);
CREATE TABLE IF NOT EXISTS itemcontent (id uuid PRIMARY KEY, id_user uuid NOT NULL, id_item uuid NOT NULL, ix_content TEXT NOT NULL);
CREATE INDEX itemcontent_id_user ON itemcontent (id_user);
CREATE INDEX itemcontent_id_item ON itemcontent (id_item);
CREATE TABLE IF NOT EXISTS subtask (id SERIAL PRIMARY KEY, id_task uuid NOT NULL, ix_name VARCHAR(150) NOT NULL, completed BOOLEAN NOT NULL);
CREATE TABLE IF NOT EXISTS releasenotify (id SERIAL PRIMARY KEY, email VARCHAR(150) NOT NULL);
ALTER TABLE releasenotify ADD CONSTRAINT releasenotify_email_unique UNIQUE (email);
CREATE TABLE IF NOT EXISTS colorsuggestion (id SERIAL PRIMARY KEY, description VARCHAR(100) NOT NULL, colors VARCHAR(9)[] NOT NULL);
CREATE TABLE IF NOT EXISTS namesuggestion (id SERIAL PRIMARY KEY, description VARCHAR(100) NOT NULL, ix_names VARCHAR(150)[] NOT NULL);
ALTER TABLE task ADD CONSTRAINT fk_task_id_user__id FOREIGN KEY (id_user) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE task ADD CONSTRAINT fk_task_id_item__id FOREIGN KEY (id_item) REFERENCES item(id) ON DELETE SET NULL ON UPDATE RESTRICT;
ALTER TABLE item ADD CONSTRAINT fk_item_id_user__id FOREIGN KEY (id_user) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE item ADD CONSTRAINT fk_item_id_list__id FOREIGN KEY (id_list) REFERENCES list(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE item ADD CONSTRAINT fk_item_id_category__id FOREIGN KEY (id_category) REFERENCES category(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE item ADD CONSTRAINT fk_item_id_task__id FOREIGN KEY (id_task) REFERENCES task(id) ON DELETE SET NULL ON UPDATE RESTRICT;
ALTER TABLE itemcontent ADD CONSTRAINT fk_itemcontent_id_user__id FOREIGN KEY (id_user) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE itemcontent ADD CONSTRAINT fk_itemcontent_id_item__id FOREIGN KEY (id_item) REFERENCES item(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE subtask ADD CONSTRAINT fk_subtask_id_task__id FOREIGN KEY (id_task) REFERENCES task(id) ON DELETE CASCADE ON UPDATE RESTRICT;